[package]
name = "svg_2_img"
version = "0.1.0"
edition = "2021"

[dependencies]
resvg = { version = "0.35.0", features = ["text"] }
tiny-skia = "0.10.0"
usvg = { version = "0.35.0", features = ["text"] }
clap = { version = "4.4.11", features = ["derive"] }
